EKB_BRANCH = "master-p10"
EKB_URI = "git://git@github.ibm.com/openbmc/pub-ekb;branch=${EKB_BRANCH};protocol=ssh"
EKB_REV = "5149a901545d178da5aab0ac2f97898462027279"

REQ_ATTRS_XMLS = "chips/p10/procedures/xml/attribute_info/p10_clock_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_freq_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_ipl_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_nest_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_pervasive_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_runn_attributes.xml \
           chips/p10/procedures/xml/attribute_info/p10_bars_attributes.xml \
           hwpf/fapi2/xml/attribute_info/unit_attributes.xml \
           hwpf/fapi2/xml/attribute_info/common_attributes.xml \
           hwpf/fapi2/xml/attribute_info/chip_attributes.xml"
